version: '3'

services:
  web:
      build:
        context: .
        dockerfile: ./docker/go-clean-arch/Dockerfile
      container_name: go_clean_arch_api
      ports:
        - 8080:8080
      depends_on:
        mysql:
          condition: service_healthy
      # volumes:
      #   - ./.env:/app/.env
  mysql: # Mysql container
    container_name: mysql
    platform: linux/x86_64 # M1チップ対応 (intel版の方はコメントアウトして実行してください)
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: go_clean_arch
      MYSQL_USER:     user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10